### ISSUE TITLE
Rename repository to 'docker-apache-php'

### ISSUE THREAD

**Issue by jasny** [legalthings/docker-apache-php#1]
The current name doesn't make it clear it's a docker image, so I was expecting code.

**Comment by svenstm** [comment]
The convention with docker images is that you keep the naming of the git repo and and the name of your docker image consistent. So to put docker into the name of a docker image is a bit strange:

https://hub.docker.com/r/legalthings/apache-php/

But if this will make things clearer I can rename it.

**Comment by jasny** [comment]
Maybe we could add `-image` after it instead, so `legalthings/apache-php-image`.

**Comment by svenstm** [comment]
Change the name to docker-apache-php
